apiVersion: v1
kind: Source
name: physical-ops
spec:
  kind: MySQL
  properties:
    host: mysql.default.svc.cluster.local
    user: test
    port: 3306
    ssl: false
    password: test
    database: PhysicalOperations
    tables:
      - PhysicalOperations.vehicles